/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 -t public/models/sd_base_holoprojector.glb
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function HoloProjector(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/sd_base_holoprojector.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('./models/sd_base_holoprojector.glb')
